{
 "title": "Cert-Manager Extended Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Certificates Ready",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max by(name, namespace) (certmanager_certificate_ready_status{condition=\"True\"} == 1))",
     "legendFormat": "Ready"
    }
   ]
  },
  {
   "title": "Pending Certificates",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(certmanager_certificate_ready_status{condition=\"Pending\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Failed Certificates",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  count by(condition) (\r\n    max by(name, namespace, condition) (\r\n      certmanager_certificate_ready_status == 1\r\n    )\r\n  ) and ignoring(condition) certmanager_certificate_ready_status{condition=\"Pending\"}\r\n) or on() vector(0)\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Certificates Expiring in <30 Days",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  (max by(name, namespace) (\r\n    (certmanager_certificate_expiration_timestamp_seconds - time()) / 86400\r\n  ) < bool 30) * 1\r\n)\r\n"
    }
   ]
  },
  {
   "title": "Certificate Expiration - Days Remaining",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(certmanager_certificate_expiration_timestamp_seconds - time()) / 86400"
    }
   ]
  },
  {
   "title": "Certificates by Namespace",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (namespace) (certmanager_certificate_ready_status)"
    }
   ]
  },
  {
   "title": "Certificates by Issuer",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (issuer_name) (certmanager_certificate_ready_status)"
    }
   ]
  }
 ]
}