{
 "title": "Trivy Vulnerabilities",
 "description": "Dashboard for Kube Trivy Exporter \nhttps://github.com/kaidotdev/kube-trivy-exporter\n\nFor image details install also this dashboard https://grafana.com/grafana/dashboards/12330",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "Critical",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "sum(trivy_image_vulnerabilities{severity=\"Critical\"})\r\n",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "rawSql": "SELECT\n  count(id) AS \"id\"\nFROM vulnerability\nWHERE\n  severity = 'critical'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "High",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "sum(trivy_image_vulnerabilities{severity=\"High\"})\r\n",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "rawSql": "SELECT\n  count(id) AS \"id\"\nFROM vulnerability\nWHERE\n  severity = 'high'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Medium",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "sum(trivy_image_vulnerabilities{severity=\"Medium\"})\r\n",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "rawSql": "SELECT\n  count(id) AS \"id\"\nFROM vulnerability\nWHERE\n  severity = 'medium'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Low",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "sum(trivy_image_vulnerabilities{severity=\"Low\"})\r\n",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "rawSql": "SELECT\n  count(id) AS \"id\"\nFROM vulnerability\nWHERE\n  severity = 'low'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Unkown",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "sum(trivy_image_vulnerabilities{severity=\"Unknown\"})",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "rawSql": "SELECT\n  count(id) AS \"id\"\nFROM host",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Trivy Vulnerabilities - 30d by Severity",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 8, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (severity) (\r\n  max_over_time(trivy_image_vulnerabilities{severity=~\"Critical|High|Medium|Low\"}[10d])\r\n)\r\n\r\n\r\n\r\n\r\n",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Image Vulnerabilities",
   "type": "table",
   "gridPos": { "h": 14, "w": 18, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc(\r\n  sum(trivy_image_vulnerabilities) by (image_repository)\r\n)\r\n",
     "legendFormat": "Image"
    },
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"Critical\"})",
     "legendFormat": "B"
    },
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"High\"})",
     "legendFormat": "B"
    }
   ]
  }
 ]
}